kind: Service
apiVersion: v1
metadata:
  name: demoservice
spec:
  selector:
    app: nestjs-dockerized
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-dockerized
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nestjs-dockerized
  template:
    metadata:
      labels:
        app: nestjs-dockerized
    spec:
      containers:
        - name: nestjs-dockerized
          image: nestjs-dockerized
          ports:
            - containerPort: 8080
